#cloud-config
write_files:
  - path: /var/spool/cron/crontabs/rancher
    permissions: "0600"
    owner: root
    group: rancher
    content: |
      0 */4 * * * docker run --rm --net host \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /usr/bin/docker:/usr/bin/docker \
        -e RANCHER_HOSTNAME=${rancher_hostname} \
        -e SLACK_WEBHOOK_URL=${slack_webhook} \
        -e SLACK_USERNAME=Rancher \
        -e SLACK_ICON=cow \
        --entrypoint backup finboxio/rancher-asg-server:${version}
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      # Start the cron service for backups
      crond
rancher:
  environment:
    S3_BUCKET: ${rancher_s3_bucket}
    CREDENTIALS_FILE: s3://${rancher_s3_bucket}/credentials
    SQS_URL: ${shudder_sqs_url}
    CLUSTER_CAPACITY: ${cluster_size}
    SLACK_WEBHOOK_URL: ${slack_webhook}
    SLACK_USERNAME: Rancher
    SLACK_ICON: cow
    MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    MYSQL_HOST: localhost
    MYSQL_PORT: 3306
    MYSQL_SOCKET: /var/run/mysqld/mysqld.sock
    MYSQL_DATA_DIR: /etc/mysql/data
    MYSQL_VOLUME_NAME: mysqlvol
    MYSQL_VOLUME_SIZE: ${mysql_volume_size}
    MYSQL_IMAGE: finboxio/rancher-asg-server:${version}
    MYSQLCHK_PORT: 9200
    RANCHER_ADMIN_USER: ${rancher_admin_user}
    RANCHER_ADMIN_PASSWORD: ${rancher_admin_password}
    RANCHER_MYSQL_USER: ${rancher_mysql_user}
    RANCHER_MYSQL_PASSWORD: ${rancher_mysql_password}
    RANCHER_MYSQL_DATABASE: ${rancher_mysql_database}
    RANCHER_HOSTNAME: ${rancher_hostname}
    RANCHER_SCHEME: https
    RANCHER_VERSION: v1.1.2
    RANCHER_PORT: 80
    RANCHER_PROXY_PORT: 81
    HAPROXY_HTTPS_REDIRECT: true
    HAPROXY_WWW_PORT: 8880
    HAPROXY_WWW_PROXY: 8881
    HAPROXY_MYSQL_PORT: 3307
    HAPROXY_HEALTHCHECK: /rancher-health
    TERMINATOR_PORT: 9999
  services:
    convoy:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "convoy-bootstrap" ]
      restart: always
      net: host
      pid: host
      privileged: true
      volumes:
        - /dev:/host/dev
        - /usr/bin:/host/usr/bin
        - /etc/docker:/host/etc/docker
        - /var/run/convoy:/var/run/convoy
        - /var/lib/rancher/convoy:/var/lib/rancher/convoy
    serf:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "serf-bootstrap" ]
      restart: always
      net: host
      volumes:
        - /etc/serf:/etc/serf
    haproxy-log:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "rsyslogd" ]
      command: [ "-n" ]
      restart: always
      net: host
      privileged: true
      volumes:
        - /var/log:/var/log
    haproxy-conf:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "haproxy-conf" ]
      restart: always
      net: host
      labels:
        - io.rancher.os.after=serf
      environment:
        - SLACK_*
        - HAPROXY_*
        - MYSQL_PORT
        - MYSQLCHK_PORT
        - RANCHER_PORT
        - RANCHER_HOSTNAME
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /etc/haproxy:/etc/haproxy
    haproxy:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "haproxy-bootstrap" ]
      restart: always
      net: host
      labels:
        - io.rancher.os.after=haproxy-conf,haproxy-log
      volumes:
        - /etc/haproxy:/etc/haproxy
    mysqlvol:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'mysql-volume' ]
      restart: on-failure
      net: host
      privileged: true
      labels:
        - io.rancher.os.after=convoy,haproxy
      environment:
        - MYSQL_*
        - RANCHER_*
      volumes:
        - /var/run:/var/run
        - /usr/bin/docker:/usr/bin/docker
    mysqlchk:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'mysqlchk-bootstrap' ]
      restart: always
      net: host
      labels:
        - io.rancher.os.after=mysql
      environment:
        - MYSQL_*
        - MYSQLCHK_*
      volumes:
        - /var/run:/var/run
    mysql-monitor:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'mysql-monitor' ]
      restart: always
      net: host
      labels:
        - io.rancher.os.after=mysqlvol
      environment:
        - MYSQL_*
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
    rancher-server:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'rancher-bootstrap' ]
      restart: on-failure
      net: host
      labels:
        - io.rancher.os.after=mysqlvol
      environment:
        - S3_BUCKET
        - CREDENTIALS_FILE
        - HAPROXY_MYSQL_PORT
        - RANCHER_*
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /var/lib/rancher/etc:/var/lib/rancher/etc
    shudder:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'shudder-bootstrap' ]
      restart: on-failure
      net: host
      environment:
        - SLACK_*
        - SQS_URL
        - TERMINATOR_PORT
        - RANCHER_PORT
        - CREDENTIALS_FILE
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    terminator:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ 'terminator-bootstrap' ]
      restart: on-failure
      net: host
      environment:
        - SLACK_*
        - TERMINATOR_PORT
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    status:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "monitor" ]
      restart: always
      net: host
      environment:
        - SLACK_*
        - CLUSTER_CAPACITY
        - MYSQL_ROOT_PASSWORD
        - RANCHER_HOSTNAME
        - HAPROXY_MYSQL_PORT
        - RANCHER_PORT
        - MYSQLCHK_PORT
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
    last-words:
      image: finboxio/rancher-asg-server:${version}
      entrypoint: [ "last-words" ]
      restart: always
      net: host
      tty: true
      labels:
        - io.rancher.os.scope=system
      environment:
        - SLACK_*
